
import { DailyWorkout, formatDateForICS } from './training-plan-utils';

export interface ICSGenerationOptions {
  userName: string;
  eventName: string;
  workouts: DailyWorkout[];
}

/**
 * Generates the string content for an .ics iCalendar file.
 */
export function generateICSContent(options: ICSGenerationOptions): string {
  const { eventName, workouts } = options;
  const calName = `Hyrox Training Plan: ${eventName}`;
  const prodId = '-//HybridX Hub//Training Plan//EN';

  let icsString = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    `PRODID:${prodId}`,
    `NAME:${calName}`,
    `X-WR-CALNAME:${calName}`,
    'BEGIN:VTIMEZONE',
    'TZID:Europe/London',
    'LAST-MODIFIED:20201011T015911Z',
    'TZURL:http://tzurl.org/zoneinfo-outlook/Europe/London',
    'X-LIC-LOCATION:Europe/London',
    'BEGIN:DAYLIGHT',
    'TZNAME:BST',
    'TZOFFSETFROM:+0000',
    'TZOFFSETTO:+0100',
    'DTSTART:19700329T010000',
    'RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU',
    'END:DAYLIGHT',
    'BEGIN:STANDARD',
    'TZNAME:GMT',
    'TZOFFSETFROM:+0100',
    'TZOFFSETTO:+0000',
    'DTSTART:19701025T020000',
    'RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU',
    'END:STANDARD',
    'END:VTIMEZONE',
  ].join('\r\n');

  workouts.forEach(workout => {
    // Escape special characters in ICS format
    const escapeICS = (str: string) => str.replace(/\\/g, '\\\\').replace(/;/g, '\\;').replace(/,/g, '\\,').replace(/\n/g, '\\n');
    
    const summary = escapeICS(`Hyrox Workout: ${workout.workoutTitle}`);
    
    const description = escapeICS(
        workout.exercises.map(ex => `• ${ex.name}: ${ex.details}`).join('\\n\\n') +
        `\\n\\n---\\nGenerated by HybridX Hub for ${eventName}`
    );

    const startDate = formatDateForICS(workout.date);
    // For all-day events, DTEND should be the day after DTSTART
    const endDate = formatDateForICS(new Date(workout.date.getTime() + 24 * 60 * 60 * 1000));
    const uid = `${startDate}-${workout.day}@hybridx.club`;

    icsString += [
      '',
      'BEGIN:VEVENT',
      `DTSTART;VALUE=DATE:${startDate}`,
      `DTEND;VALUE=DATE:${endDate}`,
      `DTSTAMP:${formatDateForICS(new Date())}Z`,
      `UID:${uid}`,
      `SUMMARY:${summary}`,
      `DESCRIPTION:${description}`,
      'TRANSP:TRANSPARENT', // Show as "Free" in calendar
      'END:VEVENT',
    ].join('\r\n');
  });

  icsString += '\r\nEND:VCALENDAR';

  return icsString;
}


/**
 * Triggers a browser download of the generated .ics file.
 */
export function downloadTrainingPlanICS(options: ICSGenerationOptions): void {
  const icsContent = generateICSContent(options);
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8;' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  const fileName = `Hyrox-Plan-${options.eventName.replace(/\s+/g, '-')}.ics`;
  link.setAttribute('download', fileName);
  
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
