
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { DailyWorkout, formatDate, formatDateShort, getWeekNumber } from './training-plan-utils';

// Brand colors
const BRAND_PRIMARY = '#FF6B35'; // Accent color
const BRAND_DARK = '#1A1A1A';
const BRAND_GRAY = '#666666';
const BRAND_LIGHT_GRAY = '#F5F5F5';

export interface PDFGenerationOptions {
  userName: string;
  eventName: string;
  eventDate: string;
  userEmail: string;
  programName: string;
  programDescription: string;
  workouts: DailyWorkout[];
}

/**
 * Generate a beautifully formatted PDF training plan
 */
export function generateTrainingPlanPDF(options: PDFGenerationOptions): jsPDF {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  let yPosition = 20;

  // Helper function to add a new page with header
  const addPageWithHeader = () => {
    doc.addPage();
    yPosition = 15;
    // Add small header on subsequent pages
    doc.setFontSize(10);
    doc.setTextColor(BRAND_GRAY);
    doc.text('HybridX - Hyrox Training Plan', pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 10;
  };

  // Helper to check if we need a new page
  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - 20) {
      addPageWithHeader();
      return true;
    }
    return false;
  };

  // ==================== COVER PAGE ====================
  // Brand accent bar at top
  doc.setFillColor(BRAND_PRIMARY);
  doc.rect(0, 0, pageWidth, 8, 'F');

  yPosition = 30;

  // Logo/Brand Name
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(BRAND_PRIMARY);
  doc.text('HYBRIDX', pageWidth / 2, yPosition, { align: 'center' });

  yPosition += 10;
  doc.setFontSize(18);
  doc.setTextColor(BRAND_DARK);
  doc.setFont('helvetica', 'normal');
  doc.text(`${options.userName}'s Personal`, pageWidth / 2, yPosition, { align: 'center' });

  yPosition += 12;
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('HYROX TRAINING PLAN', pageWidth / 2, yPosition, { align: 'center' });

  yPosition += 25;

  // Event Details Box
  doc.setFillColor(BRAND_LIGHT_GRAY);
  doc.roundedRect(20, yPosition, pageWidth - 40, 50, 3, 3, 'F');

  yPosition += 15;
  doc.setFontSize(12);
  doc.setTextColor(BRAND_DARK);
  doc.setFont('helvetica', 'bold');
  doc.text('Your Race:', pageWidth / 2, yPosition, { align: 'center' });

  yPosition += 8;
  doc.setFontSize(14);
  doc.setTextColor(BRAND_PRIMARY);
  doc.text(options.eventName, pageWidth / 2, yPosition, { align: 'center' });

  yPosition += 8;
  doc.setFontSize(12);
  doc.setTextColor(BRAND_DARK);
  doc.text(formatDate(new Date(options.eventDate)), pageWidth / 2, yPosition, { align: 'center' });

  yPosition += 20;
  doc.setFontSize(10);
  doc.setTextColor(BRAND_GRAY);
  doc.setFont('helvetica', 'normal');
  doc.text(`Prepared exclusively for ${options.userName}`, pageWidth / 2, yPosition, { align: 'center' });

  yPosition += 30;

  // Program Description
  doc.setFontSize(11);
  doc.setTextColor(BRAND_DARK);
  const descriptionLines = doc.splitTextToSize(options.programDescription, pageWidth - 40);
  doc.text(descriptionLines, pageWidth / 2, yPosition, { align: 'center', maxWidth: pageWidth - 40 });

  yPosition += descriptionLines.length * 6 + 20;

  // Key Information Box
  doc.setDrawColor(BRAND_PRIMARY);
  doc.setLineWidth(0.5);
  doc.rect(20, yPosition, pageWidth - 40, 40);

  yPosition += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(BRAND_DARK);
  doc.text('> Training Duration: 12 Weeks (84 Days)', 25, yPosition);
  yPosition += 7;
  doc.text(`> Start Date: ${formatDate(options.workouts[0].date)}`, 25, yPosition);
  yPosition += 7;
  doc.text(`> Race Day: ${formatDate(new Date(options.eventDate))}`, 25, yPosition);
  yPosition += 7;
  doc.text('> Workouts: 3-4 sessions per week', 25, yPosition);

  yPosition += 25;

  // Footer on cover page
  doc.setFontSize(8);
  doc.setTextColor(BRAND_GRAY);
  doc.setFont('helvetica', 'italic');
  doc.text('Generated by HybridX Hub - Your path to peak performance', pageWidth / 2, pageHeight - 15, { align: 'center' });

  // ==================== TRAINING PLAN PAGES ====================
  addPageWithHeader();
  yPosition += 5;

  // Title for training plan section
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(BRAND_PRIMARY);
  doc.text('YOUR 12-WEEK TRAINING SCHEDULE', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 15;

  let currentWeek = 0;

  options.workouts.forEach((workout, index) => {
    const weekNumber = getWeekNumber(workout.day);

    // Add week header if we're starting a new week
    if (weekNumber !== currentWeek) {
      currentWeek = weekNumber;

      checkPageBreak(30);

      // Week separator
      if (index > 0) {
        yPosition += 5;
      }

      doc.setFillColor(BRAND_PRIMARY);
      doc.rect(20, yPosition, pageWidth - 40, 10, 'F');

      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(255, 255, 255);
      doc.text(`WEEK ${weekNumber}`, 25, yPosition + 7);

      yPosition += 15;
    }

    // Calculate space needed for this workout
    const exerciseCount = workout.exercises.length;
    // Base space (header) + space per exercise line (estimate) + notes box space
    const spaceNeeded = 25 + (exerciseCount * 6) + 30;

    checkPageBreak(spaceNeeded);

    // Day header
    doc.setFillColor(BRAND_LIGHT_GRAY);
    doc.roundedRect(20, yPosition, pageWidth - 40, 12, 2, 2, 'F');

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(BRAND_DARK);
    doc.text(`Day ${workout.day}`, 25, yPosition + 8);
    
    // Add Checkbox
    doc.setDrawColor(BRAND_DARK);
    doc.setLineWidth(0.3);
    doc.rect(pageWidth - 45, yPosition + 3.5, 5, 5); // x, y, width, height
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(BRAND_GRAY);
    doc.text('Done', pageWidth - 38, yPosition + 8);


    doc.setFont('helvetica', 'normal');
    doc.setTextColor(BRAND_GRAY);
    doc.text(formatDateShort(workout.date), pageWidth / 2, yPosition + 8, { align: 'center' });

    yPosition += 15;

    // Workout title
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(BRAND_PRIMARY);
    doc.text(workout.workoutTitle, 25, yPosition);
    yPosition += 7;

    // Exercises
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(BRAND_DARK);

    workout.exercises.forEach((exercise) => {
      checkPageBreak(10);

      // Exercise name (bold)
      doc.setFont('helvetica', 'bold');
      doc.text(`• ${exercise.name}:`, 28, yPosition);

      // Exercise details (normal)
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(BRAND_GRAY);
      const detailsX = 28 + doc.getTextWidth(`• ${exercise.name}: `) + 2;
      const detailsLines = doc.splitTextToSize(exercise.details, pageWidth - detailsX - 25);
      doc.text(detailsLines, detailsX, yPosition);

      yPosition += detailsLines.length * 5;
      doc.setTextColor(BRAND_DARK);
    });

    yPosition += 4; // Space before notes
    
    // Notes Box
    checkPageBreak(25);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(BRAND_DARK);
    doc.text('Notes:', 25, yPosition);
    
    doc.setDrawColor(BRAND_GRAY);
    doc.setLineWidth(0.2);
    doc.roundedRect(25, yPosition + 2, pageWidth - 50, 18, 2, 2);
    
    yPosition += 25; // Height of notes box + padding

    yPosition += 4;
  });

  // ==================== FINAL PAGE - MOTIVATIONAL CLOSE ====================
  addPageWithHeader();
  yPosition = pageHeight / 2 - 40;

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(BRAND_PRIMARY);
  doc.text(`${options.userName.toUpperCase()}, YOU'RE READY TO SUCCEED!`, pageWidth / 2, yPosition, { align: 'center' });

  yPosition += 15;
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(BRAND_DARK);
  const motivationText = [
    `${options.userName}, this plan is your roadmap to success. Trust the process,`,
    'show up consistently, and watch yourself transform.',
    '',
    'Every champion was once a beginner who refused to give up.',
    '',
    'See you at the finish line!'
  ];
  motivationText.forEach(line => {
    doc.text(line, pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 7;
  });

  yPosition += 20;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(BRAND_PRIMARY);
  doc.text('- Team HybridX', pageWidth / 2, yPosition, { align: 'center' });

  return doc;
}

/**
 * Generate and trigger download of the PDF
 */
export function downloadTrainingPlanPDF(options: PDFGenerationOptions): void {
  const pdf = generateTrainingPlanPDF(options);
  const fileName = `HybridX-Hyrox-Training-Plan-${formatDateShort(new Date(options.eventDate))}.pdf`;
  pdf.save(fileName);
}
