import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { TrainingPlan, WorkoutDay } from './csv-parser';
import { format } from 'date-fns';

// Define styles matching your brand
const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#FFFFFF',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottom: '3px solid #fadb5c',
    paddingBottom: 20,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: '#000000',
    marginBottom: 4,
  },
  eventInfo: {
    fontSize: 12,
    color: '#666666',
    marginTop: 10,
  },
  description: {
    fontSize: 11,
    color: '#333333',
    lineHeight: 1.5,
    marginBottom: 20,
    padding: 15,
    backgroundColor: '#f9f9f9',
    borderLeft: '4px solid #fadb5c',
  },
  workoutDay: {
    marginBottom: 20,
    pageBreakInside: 'avoid',
  },
  dayHeader: {
    backgroundColor: '#000000',
    color: '#FFFFFF',
    padding: 10,
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dayNumber: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  dayDate: {
    fontSize: 12,
  },
  workoutTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 8,
    paddingLeft: 10,
    borderLeft: '3px solid #fadb5c',
  },
  exerciseRow: {
    marginBottom: 6,
    paddingLeft: 15,
  },
  exerciseName: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#000000',
    marginBottom: 2,
  },
  exerciseDetails: {
    fontSize: 10,
    color: '#333333',
    paddingLeft: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 9,
    color: '#999999',
    borderTop: '1px solid #eeeeee',
    paddingTop: 10,
  },
  pageNumber: {
    fontSize: 9,
    color: '#999999',
  },
  raceDay: {
    backgroundColor: '#fadb5c',
    color: '#000000',
    padding: 20,
    marginBottom: 8,
    textAlign: 'center',
  },
  raceDayTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 5,
  },
});

interface PDFDocumentProps {
  trainingPlan: TrainingPlan;
}

export const TrainingPlanPDF: React.FC<PDFDocumentProps> = ({ trainingPlan }) => {
  const formatDate = (dateString: string) => {
    return format(new Date(dateString), 'EEEE, MMMM d, yyyy');
  };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>{trainingPlan.programName}</Text>
          <Text style={styles.subtitle}>Personalized Training Plan</Text>
          <Text style={styles.eventInfo}>Event: {trainingPlan.eventName}</Text>
          <Text style={styles.eventInfo}>Race Date: {formatDate(trainingPlan.eventDate)}</Text>
          <Text style={styles.eventInfo}>Athlete: {trainingPlan.userEmail}</Text>
        </View>

        {/* Description */}
        <View style={styles.description}>
          <Text>{trainingPlan.programDescription}</Text>
        </View>

        {/* Workouts */}
        {trainingPlan.workouts.slice(0, 10).map((workout) => (
          <WorkoutDayView key={workout.day} workout={workout} />
        ))}

        {/* Footer */}
        <Text style={styles.footer} fixed>
          Generated by HybridX • www.hybridx.com
        </Text>
      </Page>

      {/* Additional pages for remaining workouts */}
      {Array.from({ length: Math.ceil((trainingPlan.workouts.length - 10) / 12) }).map((_, pageIndex) => {
        const startIdx = 10 + pageIndex * 12;
        const endIdx = startIdx + 12;
        const pageWorkouts = trainingPlan.workouts.slice(startIdx, endIdx);

        return (
          <Page key={`page-${pageIndex}`} size="A4" style={styles.page}>
            {pageWorkouts.map((workout) => (
              <WorkoutDayView key={workout.day} workout={workout} />
            ))}
            <Text style={styles.footer} fixed>
              Generated by HybridX • www.hybridx.com
            </Text>
          </Page>
        );
      })}
    </Document>
  );
};

const WorkoutDayView: React.FC<{ workout: WorkoutDay }> = ({ workout }) => {
  const formatDate = (dateString: string) => {
    return format(new Date(dateString), 'EEE, MMM d, yyyy');
  };

  const isRaceDay = workout.day === 84;

  if (isRaceDay) {
    return (
      <View style={styles.workoutDay}>
        <View style={styles.raceDay}>
          <Text style={styles.raceDayTitle}>🏆 RACE DAY! 🏆</Text>
          <Text style={{ fontSize: 14 }}>Day {workout.day} • {formatDate(workout.date)}</Text>
        </View>
        {workout.exercises.map((exercise, idx) => (
          <View key={idx} style={styles.exerciseRow}>
            <Text style={styles.exerciseName}>{exercise.exerciseName}</Text>
            <Text style={styles.exerciseDetails}>{exercise.exerciseDetails}</Text>
          </View>
        ))}
      </View>
    );
  }

  return (
    <View style={styles.workoutDay}>
      <View style={styles.dayHeader}>
        <Text style={styles.dayNumber}>Day {workout.day}</Text>
        <Text style={styles.dayDate}>{formatDate(workout.date)}</Text>
      </View>
      <Text style={styles.workoutTitle}>{workout.workoutTitle}</Text>
      {workout.exercises.map((exercise, idx) => (
        <View key={idx} style={styles.exerciseRow}>
          <Text style={styles.exerciseName}>{exercise.exerciseName}</Text>
          <Text style={styles.exerciseDetails}>{exercise.exerciseDetails}</Text>
        </View>
      ))}
    </View>
  );
};
